name: GitHub Actions Demo
run-name: ğŸ‘¨â€ğŸ’»${{ github.actor }} is testing
on: [ push ]
jobs:

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository ${{ github.repository }} on branch ${{ github.ref }} ...
        uses: actions/checkout@v4
      - name: Listing source files ...
        run: |
          ls ${{ github.workspace }}/lib -R
          echo "Listing test files ..."
          ls ${{ github.workspace }}/test -R
      - name: Listing test files ...
        run: |
          ls ${{ github.workspace }}/test -R
      - name: Setting up Flutter ...
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
      - run: flutter --version
      - run: flutter analyze
      - run: flutter pub get
      - run: flutter test
      - run: flutter test integration_test
      - run: flutter build apk
      - run: flutter build appbundle
      - run: echo "job status is ${{ job.status }}."